### ISSUE TITLE
Utiliser orderProduct plutôt que product dans GoogleTagService::getOrderProductItems()

### ISSUE THREAD

**Issue by mdevaud** [thelia-modules/GoogleTagManager#22]
Quand on crée un event ecommerce via une order, on essaie de récupérer le produit associé au productSaleElementsId d'orderProduct. 

Problème  : le champ productSaleElementsId d'orderProduct est nullable  ce qui provoque une erreur lors du paiement (réglé avec #21 mais qui donne des stats ecommerce incomplètes)

**Comment by zawaze** [comment]
See https://github.com/thelia-modules/GoogleTagManager/pull/23
